### ISSUE TITLE
Constantly getting Errors

### ISSUE THREAD

**Issue by ApolloDev0** [Prince781/vala-vscode#12]
So i've been using the vala extension for a couple of days now, and everytime im coding with it vscode just keeps highlighting errors i dont understand why this happens?, also the code executes and work fine but everything just  starts showing errors.

**Comment by Prince781** [comment]
Hi,

Can you provide more detail, please?

**Comment by ApolloDev0** [comment]
Thanks for replying on twitter, i still haven't setup the meson build system as i'm still learning the basics of vala

**Comment by Prince781** [comment]
To get a feel for this (how to use Meson with Vala), look at the https://github.com/benwaffle/vala-language-server project. Also, see https://mesonbuild.com/Vala.html to learn more about integrating Meson with Vala projects. 

Closing as this is not a bug.
