### ISSUE TITLE
Consider adding formatter and/or linter support

### ISSUE THREAD

**Issue by stsdc** [Prince781/vala-vscode#16]
Would be nice to have linting and formatting out of the box.

**Comment by elsiehupp** [comment]
@elementary OS has [opinions on code style](https://docs.elementary.io/develop/writing-apps/code-style) that might be a useful reference.

**Comment by stsdc** [comment]
@elsiehupp moreover, there is a [linter](https://github.com/vala-lang/vala-lint) based on this guidelines. Would be cool to have all its suggestions inside editor.

**Comment by Prince781** [comment]
This is something that belongs in the language server. Please refer to https://github.com/Prince781/vala-language-server/issues/212
