### ISSUE TITLE
Inline error/problem highlighting?

### ISSUE THREAD

**Issue by elsiehupp** [Prince781/vala-vscode#17]
I definitely appreciate the syntax coloring, but VS Code's interactive code annotation can go a bit further. For example, with Vala, if I type `vala <filename>` in the terminal, it will give me a list of syntax errors, improperly defined symbols, etc.—line and column numbers and all!—while by contrast [the official Python VS Code extension](https://github.com/Microsoft/vscode-python) highlights these sorts of issues using red underlines.

Basically, what would be involved in adding this sort of inline error/problem highlighting? This is somewhat related to https://github.com/Prince781/vala-vscode/issues/16, except that it shouldn't require writing the underlying rules from scratch, since the Vala compiler already provides them. Indeed, If you Cmd-Click on the filename and line/column number in the terminal, VS Code will open the file and scroll to that location, so all the necessary information is already there.

**Comment by elsiehupp** [comment]
The better comparison might be the official [OmniSharp extension](https://github.com/OmniSharp/omnisharp-vscode) for VS Code, since Vala and C# are much, much more similar to each other than they are to Python. I'm not very good with JavaScript or TypeScript, but might it be possible to port some of the OmniSharp logic over to here?

**Comment by stsdc** [comment]
Do You mean something like this?
![obraz](https://user-images.githubusercontent.com/6031763/149677159-f77b1cc0-aecb-4dde-882a-a50d6fab2795.png)

**Comment by elsiehupp** [comment]
@stsdc yes, exactly that. (Though the particular instance you are showing is warnings, i.e. yellow underlines, rather than errors, i.e. red underlines.)

**Comment by elsiehupp** [comment]
I mean, the functionality may very well already exist, but if it does, it doesn't appear to be enabled by default.

**Comment by elsiehupp** [comment]
And if it does exist, instructions for enabling and using it are absent from the [README.md](https://github.com/Prince781/vala-vscode/blob/b59c7494f1c702061226ae481bb63b983eddff0e/README.md).

**Comment by stsdc** [comment]
Here is an error ;)

![obraz](https://user-images.githubusercontent.com/6031763/149677461-65f58921-1c7a-479f-aa1b-e012edae38aa.png)

There is an:

> NOTE: in order to get code intelligence, you must install the Vala Language Server (https://github.com/benwaffle/vala-language-server).

**Comment by elsiehupp** [comment]
Thank you for the explanation. The README could be a lot clearer, though. What I mean is that instead of "code intelligence" it could say something more specific like "inline problem highlighting".

**Comment by elsiehupp** [comment]
(I mean, I could do a pull request with that change to the README.)

**Comment by Prince781** [comment]
@elsiehupp 
> Thank you for the explanation. The README could be a lot clearer, though. What I mean is that instead of "code intelligence" it could say something more specific like "inline problem highlighting".

Neither this plugin nor the language server provide "inline problem highlighting." That depends on how the editor chooses to render the diagnostics. This plugin provides syntax highlighting and exposes a way for VS Code to start a language server (if one is installed) to communicate with using the Language Server Protocol, to provide semantic analysis. This is also how the other extensions work—C/C++, Python, C#, etc—you need to have a language server for these languages installed to go beyond syntax highlighting. It's just that some of these extensions will download the server and install it for you.

**Comment by elsiehupp** [comment]
You clearly do not respect the work of QA reporters. I will get back to you when I have the energy and inclination to do yet more of your job for you for free.

**Comment by elsiehupp** [comment]
For the time being I’m unsubscribing from this Issue request. I did write more substantive feedback, but I’m just going to sit on it for now.

**Comment by Prince781** [comment]
Anyway, I'm closing this issue since the question posed has been answered.
