### ISSUE TITLE
Publish to open-vsx

### ISSUE THREAD

**Issue by benwaffle** [Prince781/vala-vscode#9]
https://open-vsx.org/

This is the extension repo used by https://vscodium.com/

**Comment by Prince781** [comment]
Hmmm...I still don't understand why this is needed. I assume "VSCode-compatible editor" means "editor forked from vscode", in which case it will be able to install extensions from marketplace.visualstudio.com, right?

In fact, I'm pretty sure any free version of vscode could just filter out extensions on the marketplace with non-free licenses. So why does this website even exist?

**Comment by benwaffle** [comment]
The point of vscodium is to strip out non-free parts of vscode (e.g. telemetry/tracking), not to restrict to free extensions.

vscodium can't use the regular marketplace for legal reasons, so they switched to open-vsx

**Comment by Prince781** [comment]
> The point of vscodium is to strip out non-free parts of vscode (e.g. telemetry/tracking)

I thought this stuff is only present in Microsoft's customization. The default vscode doesn't have any non-free components, right? And I think on Arch you can install the default vscode, which will use the VS marketplace when downloading extensions.

**Comment by benwaffle** [comment]
i've been modifying internal vscodium files to point it back to microsoft's marketplace

**Comment by Prince781** [comment]
Done. https://open-vsx.org/extension/prince781/vala
